language: php

php:
  - 5.3
  - 5.4

before_script:
    - composer self-update
    - cp app/config/parameters.yml.test app/config/parameters.yml
    - php -d memory_limit=-1 composer install

script: phpunit -c app
